### ISSUE TITLE
Structure

### ISSUE THREAD

**Issue by jpmmcneill** [jpmmcneill/jpmmcneill.github.io#2]
I need to decide on what a v1 of structure for the site should be

**Comment by jpmmcneill** [comment]
My thoughts (in yaml form):

```
pages:
  - homepage:
    url: https://jpmmcneill.github.io/home/
    description: landing page. contains links to sub landing pages as below
  - reviews:
    url: https://jpmmcneill.github.io/reviews/
    description: page with a list of things that i'm reviewing. Ideally this would be a simple page with a list of urls to subpages that have the actual reviews
    subpages:
    - product_1
      url: https://jpmmcneill.github.io/reviews/product_1
    - etc...
  - systems:
    url: https://jpmmcneill.github.io/systems/
    description: landing page for ecology project (note that in principle, this could be a subpage of a larger projects page)
  - problems:
    url: https://jpmmcneill.github.io/problems/
    description: list of code / physics problems
  - misc:
    url: https://jpmmcneill.github.io/misc/
    description: other stuff (TTRPGS, podcasts, books etc)
```
```
